### ISSUE TITLE
Error when using jsreport.binary.osx.ph2 on MacOS High Sierra

### ISSUE THREAD

**Issue by gecko-8** [jsreport/jsreport-dotnet#20]
Hi there,
I have an ASP.NET Core 2 app using jsreport in a class library to create a pdf from some html. I've added both the jsreport.Local and jsreport.Binary.OsX.Ph2 packages. When I run it, an JsReportBinaryException is thrown. Interestingly when I run the exact same code in a console app, it sometimes works (first couple tries failed and then it started working). I also tried the same code ina  console app on Windows (jsreport.Binary package) with no issues.

The code in my library is as follows:
```
...
using jsreport.Local;
using jsreport.Types;

namespace MyProject.Repositories
{
    public class BookRepository : IBookRepository
    {
        ...

        private async Task CreatePdf()
        {
            try
            {
                var rs = new LocalReporting()
                    .UseBinary(jsreport.Binary.OSX.Ph2.JsReportBinary.GetBinary())
                    .AsUtility()
                    .Create();

                var report = await rs.RenderAsync(new RenderRequest
                {
                    Template = new Template
                    {
                        Recipe = Recipe.PhantomPdf,
                        Engine = Engine.None,
                        Content = "Hello"
                    }
                });

                using (var fs = File.Create("out.pdf"))
                {
                    report.Content.CopyTo(fs);
                }
            }
            catch (JsReportBinaryException ex)
            {
                var e = ex;
            }
        }

        ...
    }
}
```
Project file:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="jsreport.binary.osx.ph2" Version="1.10.0" />
    <PackageReference Include="jsreport.local" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="2.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.2" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.1.1" />
  </ItemGroup>
  <ItemGroup>
    ...
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
  </ItemGroup>
</Project>
```

Exception Message:
```
"Error rendering report: rendering has finished with errors:Error: An error occurred while trying to execute the command:    at onCriticalError ([eval]:36106:25)    at tryCatcher ([eval]:9718:23)    at Promise._settlePromiseFromHandler ([eval]:38241:31)    at Promise._settlePromise ([eval]:38298:18)    at Promise._settlePromise0 ([eval]:38343:10)    at Promise._settlePromises ([eval]:38418:18)    at Async._drainQueue ([eval]:4650:16)    at Async._drainQueues ([eval]:4660:10)    at Immediate.Async.drainQueues [as _onImmediate] ([eval]:4534:14)    at processImmediate [as _immediateCallback] (timers.js:396:17) {\"originalError\":{\"remoteStack\":\"Error: Command failed: /var/folders/_9/vkdjn0vn43l032b80b1q87r40000gp/T/jsreport/compile/jsreport-1.9.2-ryBaRwiyG/phantomjs.exe --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any /var/folders/_9/vkdjn0vn43l032b80b1q87r40000gp/T/jsreport/compile/jsreport-1.9.2-ryBaRwiyG/standaloneScript.js /var/folders/_9/vkdjn0vn43l032b80b1q87r40000gp/T/jsreport/fab79ab0-6035-11e8-9796-059a117b593asettings.html\\n, Segmentation fault error: if you are using macOS Sierra with phantomjs < 2 remember that phantomjs < 2 does not work there and has bugs (https://github.com/ariya/phantomjs/issues/14558), try to upgrade to phantom 2 if using macOS Sierra\\n    at ChildProcess.exithandler (child_process.js:214:12)\\n    at emitTwo (events.js:87:13)\\n    at ChildProcess.emit (events.js:172:7)\\n    at maybeClose (internal/child_process.js:854:16)\\n    at Socket.<anonymous> (internal/child_process.js:330:11)\\n    at emitOne (events.js:77:13)\\n    at Socket.emit (events.js:169:7)\\n    at Pipe._onclose (net.js:487:12)\"}}(Original) Error: Error during rendering report: Command failed: /var/folders/_9/vkdjn0vn43l032b80b1q87r40000gp/T/jsreport/compile/jsreport-1.9.2-ryBaRwiyG/phantomjs.exe --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any /var/folders/_9/vkdjn0vn43l032b80b1q87r40000gp/T/jsreport/compile/jsreport-1.9.2-ryBaRwiyG/standaloneScript.js /var/folders/_9/vkdjn0vn43l032b80b1q87r40000gp/T/jsreport/fab79ab0-6035-11e8-9796-059a117b593asettings.html, Segmentation fault error: if you are using macOS Sierra with phantomjs < 2 remember that phantomjs < 2 does not work there and has bugs (https://github.com/ariya/phantomjs/issues/14558), try to upgrade to phantom 2 if using macOS Sierra    at [eval]:39138:23    at ConcatStream.<anonymous> ([eval]:44860:43)    at emitNone (events.js:72:20)    at ConcatStream.emit (events.js:166:7)    at finishMaybe ([eval]:4229:14)    at afterWrite ([eval]:4115:3)    at nextTickCallbackWithManyArgs (node.js:486:18)    at process._tickCallback (node.js:384:17) {\"remoteStack\":\"Error: Command failed: /var/folders/_9/vkdjn0vn43l032b80b1q87r40000gp/T/jsreport/compile/jsreport-1.9.2-ryBaRwiyG/phantomjs.exe --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any /var/folders/_9/vkdjn0vn43l032b80b1q87r40000gp/T/jsreport/compile/jsreport-1.9.2-ryBaRwiyG/standaloneScript.js /var/folders/_9/vkdjn0vn43l032b80b1q87r40000gp/T/jsreport/fab79ab0-6035-11e8-9796-059a117b593asettings.html\\n, Segmentation fault error: if you are using macOS Sierra with phantomjs < 2 remember that phantomjs < 2 does not work there and has bugs (https://github.com/ariya/phantomjs/issues/14558), try to upgrade to phantom 2 if using macOS Sierra\\n    at ChildProcess.exithandler (child_process.js:214:12)\\n    at emitTwo (events.js:87:13)\\n    at ChildProcess.emit (events.js:172:7)\\n    at maybeClose (internal/child_process.js:854:16)\\n    at Socket.<anonymous> (internal/child_process.js:330:11)\\n    at emitOne (events.js:77:13)\\n    at Socket.emit (events.js:169:7)\\n    at Pipe._onclose (net.js:487:12)\"}"
```

And the stack trace from the exception:
```
"   at jsreport.Local.Internal.LocalUtilityReportingService.<RenderAsync>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n   at Admazing.Repositories.BookRepository.<CreatePdf>d__20.MoveNext() in /Data/GIT/verticalmotion_admazingbackend/source/Admazing.Repositories/BookRepository.cs:line 522"
```

Any thoughts would be appreciated.

**Comment by gecko-8** [comment]
Hmm, magically started working. Shrug. Closing.

**Comment by huxaiphaer** [comment]
How did it magically start working, because am using a mac with the same issue?

**Comment by gecko-8** [comment]
@huxaiphaer sorry, I wish I could tell you. I didn't change anything and it just started working. I don't really remember much else about the project.

**Comment by huxaiphaer** [comment]
Hey, I  managed to get it to work via this [issue](https://github.com/jsreport/jsreport-dotnet-example-webapp/issues/5#issuecomment-513750362)
