### ISSUE TITLE
Running in Azure - Timeout when executing in phantom

### ISSUE THREAD

**Issue by penihel** [jsreport/jsreport-dotnet#24]
I Follow this steps https://jsreport.net/learn/dotnet-local

Works on my local machine, but i get this error on azure webapp

```
Error rendering report: rendering has finished with errors:Error: 
An error occurred while trying to execute the command:    
at onCriticalError ([eval]:29603:25)    
at tryCatcher ([eval]:36038:23)    
at Promise._settlePromiseFromHandler ([eval]:34061:31)    
at Promise._settlePromise ([eval]:34118:18)    
at Promise._settlePromise0 ([eval]:34163:10)    
at Promise._settlePromises ([eval]:34238:18)    
at Async._drainQueue ([eval]:31008:16)    
at Async._drainQueues ([eval]:31018:10)    
at Immediate.Async.drainQueues [as _onImmediate] ([eval]:30892:14)    
at processImmediate [as _immediateCallback] (timers.js:396:17) 
{"originalError":{"remoteStack":"Error: 
Timeout when executing in phantom\n    
at null._onTimeout (jsreportRuntime.js:219991:26)\n    
at Timer.unrefdHandle (timers.js:318:16)"}}
(Original) Error: Error during rendering report: Timeout when executing in phantomlogs:+0      
Starting rendering request 2+0      
Rendering anonymous template 
{ recipe:phantom-pdf,engine:none}+0      
Data item not defined for this template.+15     
Resources not defined for this template.+15     
Base url not specified, skipping its injection.+15     
Rendering engine none+15     
Taking compiled template from engine cache+15     
Replaced images []+15     
Executing recipe phantom-pdf    
at [eval]:36644:23    
at ConcatStream.<anonymous> ([eval]:42366:43)    
at emitNone (events.js:72:20)    
at ConcatStream.emit (events.js:166:7)    
at finishMaybe ([eval]:4229:14)    
at afterWrite ([eval]:4115:3)    
at nextTickCallbackWithManyArgs (node.js:486:18)    
at process._tickCallback (node.js:384:17) 
{"remoteStack":"Error: Timeout when executing in phantom\n    
at null._onTimeout (jsreportRuntime.js:219991:26)\n    
at Timer.unrefdHandle (timers.js:318:16)"}"
```

**Comment by penihel** [comment]
I figure out the problem.

Is about the "App service Plan". The service plan must be "basic or higher". The "free" plan has a CPU shared, and is not compatibility
