### ISSUE TITLE
Binary Errors on Mac OS X

### ISSUE THREAD

**Issue by Dafrapster** [jsreport/jsreport-dotnet#26]
I have been unable to get jsreport-dotnet to run on OS X and I am able to reproduce the issue on the sample project. I created the issue jsreport/jsreport-dotnet-example-consoleapp#3 several weeks ago and have yet to get a response and I am currently stuck waiting on a solution so I thought I the issue might get more visibility here. Below is the full text from the original issue:

> When I attempt to run the sample project on Windows it executes correctly but when I run is on Mac OS X it throws the following error on calls to RenderAsync:
>
>`An unhandled exception of type 'System.AggregateException' occurred in System.Private.CoreLib.dll: 'One or more errors occurred.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.ComponentModel.Win32Exception : Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at jsreport.Local.Internal.BinaryProcess.<InnerExecute>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable'1.ConfiguredTaskAwaiter.GetResult()
   at jsreport.Local.Internal.BinaryProcess.<ExecuteExe>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable'1.ConfiguredTaskAwaiter.GetResult()
   at jsreport.Local.Internal.LocalUtilityReportingService.<RenderAsync>d__10.MoveNext()` 
>
>**Steps To Reproduce:**
>1) Download sample project.
>2) Inclue 'jsreport.Binary.OSX' in csproj file.
>3) In program.cs change the line `.UseBinary(jsreport.Binary.JsReportBinary.GetBinary())` to reference the correct binary like so `.UseBinary(jsreport.Binary.OSX.JsReportBinary.GetBinary())`
>4) Run example project.
>
>Any help would be appreciated as I have been stuck on this issue for days.
>
 **Additional Details:**
>I think I may have found a clue as to the problem. If I run the console app dll with the mono command (instead of the dotnet command) I get a more useful error message:
>
>`Unhandled Exception:
>System.IO.FileNotFoundException: Could not load file or assembly 'jsreport.Local, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
>File name: 'jsreport.Local, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'
>[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'jsreport.Local, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
>File name: 'jsreport.Local, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'`
>
>I get a missing dll message until I have manually included all of the jsreport .dlls in the output folder. After including all of the .dll files I now get the following error:
>
>`Unhandled Exception:
>System.TypeLoadException: Could not resolve type with token 01000015 (from typeref, class/assembly System.Threading.CancellationToken, System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
>[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 01000015 (from typeref, class/assembly System.Threading.CancellationToken, System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)`

**Comment by Dafrapster** [comment]
It seems version 2.2.1 fixes the error! When I first got the issue 2.2.0 was the latest and I didn't notice jsreport-dotnet-binary-osx@2.2.1 was released right before I opened the ticket.

Thank you so much for your help!
