### ISSUE TITLE
ENOENT error in jsreport SDK

### ISSUE THREAD

**Issue by cdespinosaagmx** [jsreport/jsreport-dotnet#46]
I'm having an issue in the sdk about ENOENT error... I see Jah Blaha says one way to fix it... and it is the following code: { "useExtensionsLocationCache": false}, but i don't know how to set it in dot net SDK... maybe one file got crashed.. or something like that

I know that if i delete the folder jsreport-2.7.1-rkb7tS0VI it could be solve but i need one way to fix it without be deleting the folder each time that this issue appear.

Log:

jsreport.Local.JsReportBinaryException: Error rendering report: events.js:187      throw er; // Unhandled 'error' event      ^Error: spawn C:\Users\ITGQro3\AppData\Local\Temp\jsreport\compile\jsreport-2.7.1-rkb7tS0VI\WinRun.exe ENOENT    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)    at onErrorNT (internal/child_process.js:456:16)    at processTicksAndRejections (internal/process/task_queues.js:80:21)Emitted 'error' event on ChildProcess instance at:    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)    at onErrorNT (internal/child_process.js:456:16)    at processTicksAndRejections (internal/process/task_queues.js:80:21) {  errno: 'ENOENT',  code: 'ENOENT',  syscall: 'spawn C:\\Users\\ITGQro3\\AppData\\Local\\Temp\\jsreport\\compile\\jsreport-2.7.1-rkb7tS0VI\\WinRun.exe',  path: 'C:\\Users\\ITGQro3\\AppData\\Local\\Temp\\jsreport\\compile\\jsreport-2.7.1-rkb7tS0VI\\WinRun.exe',  spawnargs: [    'C:\\Users\\ITGQro3\\AppData\\Local\\Temp\\jsreport\\dotnet\\binary-default-2.7.1.0\\jsreport.exe',    '"D:\\snapshot\\jsreport\\jsreportStartup.js"',    '"D:\\snapshot\\jsreport\\node_modules\\jsreport-cli\\lib\\daemonInstance.js"',    '"\\\\.\\pipe\\C:\\Users\\ITGQro3\\AppData\\Local\\Temp\\jsreport\\cli\\sock\\connection.Ik846l_.sock"',    '"--node-process"'  ]}
   en jsreport.Local.Internal.LocalUtilityReportingService.<RenderAsync>d__11.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en BProSuite.Report.Controllers.ReportController.<Report>d__11.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   en BProSuite.Report.Controllers.ReportController.<GenerarReporte>d__10.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass8_0.<BeginInvokeAsynchronousActionMethod>b__1(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   en System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()

**Comment by pofider** [comment]
Hm, these errors should have been fixed :(
Could you try to delete this folder and run again?
`C:\Users\ITGQro3\AppData\Local\Temp\jsreport`

**Comment by cdespinosaagmx** [comment]
Ya i did it, it works but... i think it will happen again i wanna know if i could fix it in the sdk code

**Comment by pofider** [comment]
It would be interesting to know what is actually inside that folder
`C:\Users\ITGQro3\AppData\Local\Temp\jsreport\compile\jsreport-2.7.1-rkb7tS0VI\`
Could you include it the next time it happens? 
Thanks.

**Comment by cdespinosaagmx** [comment]
Okay. here is my actual code in c# do not pay attention to HtmlAgilityPack code.
![image](https://user-images.githubusercontent.com/62155748/77448004-f7ac6500-6db5-11ea-8020-3f873ea0a6ec.png)

**Comment by cdespinosaagmx** [comment]
I will attach the picture of the files inside jsreport-2.7.1-rkb7tS0VI when it happens.

**Comment by cdespinosaagmx** [comment]
Jah Blaha... another question. I'm trying to check if i could use WebDataRocks with your jsreport SDK but i'm having troubles, i'm passing css files and js files, and HTML from WebDataRocks examples but it is not working, WebDataRocks has a very big code inside with uglyfy code, i don't know if it is affecting the Template and Engine.

**Comment by pofider** [comment]
I recommend starting full jsreport on the side and fiddle with it. It is easier to troubleshoot with the studio than with .net.

WebDataRocks should work like any other js framework.
Maybe you just need to configure the printing trigger to start pdf creation when the WebDataRocks is fully loaded.
https://jsreport.net/learn/chrome-pdf#printing-triggers

**Comment by drewlsvern** [comment]
Was this problem ever resolved? I am experiencing the same issue as @cdespinosaagmx.

2020-08-13 11:11:07.2054||ERROR|CCMBC.Disclaimer.Merger.MainForm|One or more errors occurred. (Error rendering report: events.js:187      throw er; // Unhandled 'error' event      ^Error: spawn C:\Users\super.user\AppData\Local\Temp\jsreport\compile\jsreport-2.7.1-rkb7tS0VI\WinRun.exe ENOENT    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)    at onErrorNT (internal/child_process.js:456:16)    at processTicksAndRejections (internal/process/task_queues.js:80:21)Emitted 'error' event on ChildProcess instance at:    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)    at onErrorNT (internal/child_process.js:456:16)    at processTicksAndRejections (internal/process/task_queues.js:80:21)    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at CCMBC.Disclaimer.Merger.Core.Services.PdfDisclaimerGeneratorService.ProcessDisclaimerPdfGeneration(String outputPdfDirectory) in C:\Source\Repos\CCMBC\.NET\CCMBC.Disclaimer.Merger\CCMBC.Disclaimer.Merger.Core\Services\PdfDisclaimerGeneratorService.cs:line 50
   at CCMBC.Disclaimer.Merger.MainForm.PdfBackgroundWorker_DoWork(Object sender, DoWorkEventArgs e) in C:\Source\Repos\CCMBC\.NET\CCMBC.Disclaimer.Merger\CCMBC.Disclaimer.Merger\MainForm.cs:line 74) jsreport.Local.JsReportBinaryException: Error rendering report: events.js:187      throw er; // Unhandled 'error' event      ^Error: spawn C:\Users\super.user\AppData\Local\Temp\jsreport\compile\jsreport-2.7.1-rkb7tS0VI\WinRun.exe ENOENT    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)    at onErrorNT (internal/child_process.js:456:16)    at processTicksAndRejections (internal/process/task_queues.js:80:21)Emitted 'error' event on ChildProcess instance at:    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)    at onErrorNT (internal/child_process.js:456:16)    at processTicksAndRejections (internal/process/task_queues.js:80:21) {  errno: 'ENOENT',  code: 'ENOENT',  syscall: 'spawn C:\\Users\\super.user\\AppData\\Local\\Temp\\jsreport\\compile\\jsreport-2.7.1-rkb7tS0VI\\WinRun.exe',  path: 'C:\\Users\\super.user\\AppData\\Local\\Temp\\jsreport\\compile\\jsreport-2.7.1-rkb7tS0VI\\WinRun.exe',  spawnargs: [    'C:\\Users\\super.user\\AppData\\Local\\Temp\\jsreport\\dotnet\\binary-default-2.7.1.0\\jsreport.exe',    '"D:\\snapshot\\jsreport\\jsreportStartup.js"',    '"D:\\snapshot\\jsreport\\node_modules\\jsreport-cli\\lib\\daemonInstance.js"',    '"\\\\.\\pipe\\C:\\Users\\super.user\\AppData\\Local\\Temp\\jsreport\\cli\\sock\\connection.IUjnGbJ.sock"',    '"--node-process"'  ]}
   at jsreport.Local.Internal.LocalUtilityReportingService.RenderAsync(String requestString, CancellationToken ct)

@pofider If you would like screenshots of the directory I can post them.

**Comment by pofider** [comment]
@drewlsvern Please try it with the latest jsreport nugets, you have a bit older versions. Please update mainly jsreport.Binary and jsreport.Local.

**Comment by drewlsvern** [comment]
@pofider Thanks. Last time I checked there was no new updates. I will give this a try.

**Comment by pofider** [comment]
The binary unpacking was improved in v3 sdk we've just released.
Please try it out and come back if it doesn't help.
