### ISSUE TITLE
Issue With Docker Deployment

### ISSUE THREAD

**Issue by ArcadeRenegade** [jsreport/jsreport-dotnet#51]
Hello,

We upgraded jsreport.AspNetCore v2.1.0 and are getting an error that we have not gotten before.

According to the docs we need to run some special commands for Docker Linux container deployment. We have this in our dockerfile and it worked before but now we are getting an error.

https://jsreport.net/learn/dotnet-local#docker

```
RUN apt-get update && \   
    apt-get install -y gnupg  libgconf-2-4 wget && \
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
    apt-get update && \
    apt-get install -y google-chrome-unstable --no-install-recommends

ENV chrome:launchOptions:args --no-sandbox
```

> Command failed on instance. Return code: 100 Output: (TRUNCATED)...n-zero code: 100 Failed to build Docker image aws_beanstalk/staging-app: ces.list.d/google.list' && apt-get update && apt-get install -y google-chrome-unstable --no-install-recommends' returned a non-zero code: 100. Check snapshot logs for details. Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/03build.sh failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.

> Failed to build Docker image aws_beanstalk/staging-app: ces.list.d/google.list' && apt-get update && apt-get install -y google-chrome-unstable --no-install-recommends' returned a non-zero code: 100. Check snapshot logs for details.

It seems like the commands in the dockerfile are failing. Has anyone experienced this issue before?

**Comment by pofider** [comment]
Please use this command now.

```
RUN apt-get install -y --no-install-recommends libgconf-2-4 gnupg git curl wget ca-certificates libgconf-2-4 && \
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
    apt-get update && \  
    apt-get install -y lsb-release google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst --no-install-recommends && \
    wget https://github.com/webnicer/chrome-downloads/raw/master/x64.deb/google-chrome-stable_79.0.3945.130-1_amd64.deb && \
    dpkg -i ./google-chrome*.deb && \
    rm google-chrome*.deb

ENV chrome_launchOptions_executablePath google-chrome-stable
ENV chrome_launchOptions_args --no-sandbox,--disable-dev-shm-usage
```

**Comment by ArcadeRenegade** [comment]
Thank you very much

**Comment by ArcadeRenegade** [comment]
Hi @pofider 

We're still getting an error due to the dockerfile commands. Any ideas?

`Command failed on instance. Return code: 100 Output: (TRUNCATED)...n-zero code: 100 Failed to build Docker image aws_beanstalk/staging-app: 64.deb/google-chrome-stable_79.0.3945.130-1_amd64.deb && dpkg -i ./google-chrome*.deb && rm google-chrome*.deb' returned a non-zero code: 100. Check snapshot logs for details. Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/03build.sh failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.`

`Failed to build Docker image aws_beanstalk/staging-app: 64.deb/google-chrome-stable_79.0.3945.130-1_amd64.deb && dpkg -i ./google-chrome*.deb && rm google-chrome*.deb' returned a non-zero code: 100. Check snapshot logs for details.`

**Comment by pofider** [comment]
What base docker image you use?

**Comment by ArcadeRenegade** [comment]
Hi @pofider 

We are using mcr.microsoft.com/dotnet/core/aspnet:3.1

Here is our whole dockerfile if that helps. I tried to get the error message from the logs but unfortunately I was not successful. I also tried to run the docker commands manually to get the error message but I couldn't figure out how.

Also we are using AWS Elastic Beanstalk Linux Docker environment.

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

RUN apt-get install -y --no-install-recommends libgconf-2-4 gnupg git curl wget ca-certificates libgconf-2-4 && \
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
    apt-get update && \  
    apt-get install -y lsb-release google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst --no-install-recommends && \
    wget https://github.com/webnicer/chrome-downloads/raw/master/x64.deb/google-chrome-stable_79.0.3945.130-1_amd64.deb && \
    dpkg -i ./google-chrome*.deb && \
    rm google-chrome*.deb

ENV chrome_launchOptions_executablePath google-chrome-stable
ENV chrome_launchOptions_args --no-sandbox,--disable-dev-shm-usage

EXPOSE 80

WORKDIR /tmp

COPY . ./

ENV ASPNETCORE_URLS=http://+:80

ENTRYPOINT ["dotnet", "HouseStayAPI.dll"]

```

**Comment by pofider** [comment]
You are missing the `RUN apt-get update`  at the top.

**Comment by ArcadeRenegade** [comment]
Thanks! I will add it and give it a try.

**Comment by ArcadeRenegade** [comment]
All good now! Thank you very much, sir.

**Comment by ArcadeRenegade** [comment]
Hi @pofider 

Unfortunately, we are getting an error due to the jsreport commands in our docker file again. It seems like it is trying to downgrade google-chrome-stable and returning non-zero code.

We are running Docker running on 64bit Amazon Linux/2.15.3 w/ jsreport.Binary.Linux v2.9.0 & jsreport.AspNetCore v2.1.0 & jsreport.Local v2.2.3

We tried with jsreport.Local v2.3 as well and had the same issue.

Logs:

```  
  [0m[91m2020-08-26 21:47:24 (86.0 MB/s) - 'google-chrome-stable_79.0.3945.130-1_amd64.deb' saved [62193324/62193324]
  
  [0m[91mdpkg: warning: downgrading google-chrome-stable from 85.0.4183.83-1 to 79.0.3945.130-1
  [0m(Reading database ... 21194 files and directories currently installed.)
  Preparing to unpack .../google-chrome-stable_79.0.3945.130-1_amd64.deb ...
  Unpacking google-chrome-stable (79.0.3945.130-1) over (85.0.4183.83-1) ...
  Processing triggers for mime-support (3.62) ...
  [91mdpkg: dependency problems prevent configuration of google-chrome-stable:
   google-chrome-stable depends on libxss1; however:
    Package libxss1 is not installed.
  
  dpkg: error processing package google-chrome-stable (--install):
   dependency problems - leaving unconfigured
  [0m[91mErrors were encountered while processing:
   google-chrome-stable
  [0mThe command '/bin/sh -c apt-get install -y --no-install-recommends libgconf-2-4 gnupg git curl wget ca-certificates libgconf-2-4 &&     wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&     sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' &&     apt-get update &&     apt-get install -y lsb-release google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst --no-install-recommends &&     wget https://github.com/webnicer/chrome-downloads/raw/master/x64.deb/google-chrome-stable_79.0.3945.130-1_amd64.deb &&     dpkg -i ./google-chrome*.deb &&     rm google-chrome*.deb' returned a non-zero code: 1
  Failed to build Docker image aws_beanstalk/staging-app: /x64.deb/google-chrome-stable_79.0.3945.130-1_amd64.deb &&     dpkg -i ./google-chrome*.deb &&     rm google-chrome*.deb' returned a non-zero code: 1. Check snapshot logs for details. (Executor::NonZeroExitStatus)
```

Full dockerfile:

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

RUN apt-get update

RUN apt-get install -y --no-install-recommends libgconf-2-4 gnupg git curl wget ca-certificates libgconf-2-4 && \
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
    apt-get update && \  
    apt-get install -y lsb-release google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst --no-install-recommends && \
    wget https://github.com/webnicer/chrome-downloads/raw/master/x64.deb/google-chrome-stable_79.0.3945.130-1_amd64.deb && \
    dpkg -i ./google-chrome*.deb && \
    rm google-chrome*.deb

ENV chrome_launchOptions_executablePath google-chrome-stable
ENV chrome_launchOptions_args --no-sandbox,--disable-dev-shm-usage

EXPOSE 80

WORKDIR /tmp

COPY . ./

ENV ASPNETCORE_URLS=http://+:80

ENTRYPOINT ["dotnet", "HouseStayAPI.dll"]
```

**Comment by pofider** [comment]
Please use this in docker now.

```
# install chrome with deps, see https://github.com/jsreport/jsreport/blob/master/docker/full/Dockerfile
RUN apt-get install -y --no-install-recommends libgconf-2-4 gnupg git curl wget ca-certificates libgconf-2-4 && \
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
    apt-get update && \  
    apt-get install -y lsb-release google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst libxtst6 libxss1 --no-install-recommends
```

**Comment by ArcadeRenegade** [comment]
Thank you very much, @pofider. We were able to deploy to the web servers successfully.

Unfortunately we are getting an error when trying to render a pdf on the servers now.

I saw --no-sandbox flag was in the old docker commands, should it be added to the new one too?

```
Failed to launch chrome![0827/220519.358298:WARNING:resource_bundle.cc(426)] locale_file_path.empty() for locale [0827/220519.361423:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md (1). caused by error 
```

```
[Error] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HM2AP9LLCT4F", Request id "0HM2AP9LLCT4F:00000004": An unhandled exception was thrown by the application. jsreport.Local.JsReportBinaryException: Error rendering report: instance has been daemonized and initialized successfully (pid: 228)rendering has finished with errors:A critical error occurred while trying to execute the render command (2). Failed to launch chrome![0827/220519.358298:WARNING:resource_bundle.cc(426)] locale_file_path.empty() for locale [0827/220519.361423:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md (1). caused by error (2):-> stackError:    at onCriticalError (/snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:302:19)    at /snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:256:14    at processTicksAndRejections (internal/process/task_queues.js:97:5)caused by error (1):-> stackError: Failed to launch chrome![0827/220519.358298:WARNING:resource_bundle.cc(426)] locale_file_path.empty() for locale [0827/220519.361423:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md    at Client.render (/snapshot/jsreport/node_modules/jsreport-client/lib/client.js)    at processTicksAndRejections (internal/process/task_queues.js:97:5)    at async startRender (/snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:319:24)    at async /snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:226:22    at async Commander.executeCommand (/snapshot/jsreport/node_modules/jsreport-cli/lib/commander.js:242:22)Remote stack: Error: Failed to launch chrome![0827/220519.358298:WARNING:resource_bundle.cc(426)] locale_file_path.empty() for locale [0827/220519.361423:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md    at onClose (/snapshot/jsreport/node_modules/puppeteer/lib/Launcher.js:348:14)    at Interface.<anonymous> (/snapshot/jsreport/node_modules/puppeteer/lib/Launcher.js:337:50)    at Interface.emit (events.js:323:22)    at Interface.close (readline.js:409:8)    at Socket.onend (readline.js:187:10)    at Socket.emit (events.js:323:22)    at endReadableNT (_stream_readable.js:1204:12)    at processTicksAndRejections (internal/process/task_queues.js:84:21)
   at jsreport.Local.Internal.LocalUtilityReportingService.RenderAsync(String requestString, CancellationToken ct)
   at jsreport.AspNetCore.JsReportMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by ArcadeRenegade** [comment]
My bad, I removed the commands that set chrome launch path and args. I added them back and it is working again.

```
ENV chrome_launchOptions_executablePath google-chrome-stable
ENV chrome_launchOptions_args --no-sandbox,--disable-dev-shm-usage
```
Thank you for your help and for this library, @pofider.
