### ISSUE TITLE
AWS Linux 2 Deployment

### ISSUE THREAD

**Issue by ArcadeRenegade** [jsreport/jsreport-dotnet#53]
Hello all,

AWS ElasticBeanstalk now has .NET Core direct support for AWS Linux 2.
We have deployed our dev environment to it and are no longer using docker.

https://aws.amazon.com/blogs/developer/aws-elastic-beanstalk-adds-net-core-on-linux-platform/

However, when we try to render a pdf using jsreport we get the below error.

Is there any pre-configuration script we should set up?
I know for docker we had the commands in the docker file [as described here](https://jsreport.net/learn/dotnet-local#docker).
Is there similar commands we should run in an sh script instead?

Here is the error. Thank you for your help.

```
[Error] Microsoft.AspNetCore.Server.Kestrel: Connection id "0HM3QA27C4A4G", Request id "0HM3QA27C4A4G:00000001": An unhandled exception was thrown by the application. jsreport.Local.JsReportBinaryException: Error rendering report: instance has been daemonized and initialized successfully (pid: 18345)rendering has finished with errors:A critical error occurred while trying to execute the render command (2). Failed to launch chrome!/tmp/jsreport/compile/jsreport-2.9.0-BkIEYvyxv/chrome/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directoryTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md (1). caused by error (2):-> stackError:    at onCriticalError (/snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:302:19)    at /snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:256:14    at processTicksAndRejections (internal/process/task_queues.js:97:5)caused by error (1):-> stackError: Failed to launch chrome!/tmp/jsreport/compile/jsreport-2.9.0-BkIEYvyxv/chrome/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directoryTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md    at Client.render (/snapshot/jsreport/node_modules/jsreport-client/lib/client.js)    at processTicksAndRejections (internal/process/task_queues.js:97:5)    at async startRender (/snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:319:24)    at async /snapshot/jsreport/node_modules/jsreport-cli/lib/commands/render.js:226:22    at async Commander.executeCommand (/snapshot/jsreport/node_modules/jsreport-cli/lib/commander.js:242:22)Remote stack: Error: Failed to launch chrome!/tmp/jsreport/compile/jsreport-2.9.0-BkIEYvyxv/chrome/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directoryTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md    at onClose (/snapshot/jsreport/node_modules/puppeteer/lib/Launcher.js:348:14)    at Interface.<anonymous> (/snapshot/jsreport/node_modules/puppeteer/lib/Launcher.js:337:50)    at Interface.emit (events.js:323:22)    at Interface.close (readline.js:409:8)    at Socket.onend (readline.js:187:10)    at Socket.emit (events.js:323:22)    at endReadableNT (_stream_readable.js:1204:12)    at processTicksAndRejections (internal/process/task_queues.js:84:21)
   at jsreport.Local.Internal.LocalUtilityReportingService.RenderAsync(String requestString, CancellationToken ct)
   at jsreport.AspNetCore.JsReportMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by ArcadeRenegade** [comment]
I installed chrome manually and it works. I'll throw these into an sh script.

```
# wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
# yum -y install redhat-lsb libXScrnSaver
# yum -y localinstall google-chrome-stable_current_x86_64.rpm
```
