### ISSUE TITLE
DotNetCore 3.1 - JSReport:  Throwing (start daemonized process) error while generating PDF report in DotnetCore as middleware 

### ISSUE THREAD

**Issue by rdevidasvcm-hyniva** [jsreport/jsreport-dotnet#62]
**Description:**  Referred Assemblies - jsReport.AspNetCore 1.0.0, jsReport.Binary 1.9.1 and jsReport.Local 1.1.0. 
I have hosted the application as two sites (1. Production and 2.UAT) in One IIS web server,  The code of each Prod and UAT is located in two different folders.   Reports are getting generated in Production application.  where as in UAT application throwing the below error.

**Spent lot of time to identify the resolution article, none found.  So, connecting with you to help me on this.**

Added JsReport as services in StartUp.cs file as below:
```
services.AddJsReport(new LocalReporting()
                .KillRunningJsReportProcesses()
                .UseBinary(JsReportBinary.GetBinary())
                .RunInDirectory(Path.Combine(Directory.GetCurrentDirectory(), "jsreport", "temp"))
                .Configure(cfg => cfg.AllowLocalFilesAccess().FileSystemStore().BaseUrlAsWorkingDirectory())
                .AsUtility().Create());
```
Report generation Code:
  ```
 [HttpGet("QuestionAnswer-pdf")]
        [MiddlewareFilter(typeof(JsReportPipeline))]
        public async Task<IActionResult> QuestionAnswerPDF(long Id)
        {
            var model = await GetQuestionAnswers(Id);
            string header = $"<h3>Research Data Report: {appContext.Title}</h3>";
            HttpContext.JsReportFeature()
                .Recipe(Recipe.PhantomPdf)
                .Configure((r) => r.Template.Phantom = new Phantom
                { Footer = ReportFooter,  FooterHeight = ".55cm", Header = header, HeaderHeight = "1.4cm" });
            return View("SecurityQuestions", model);
        }
```

**Received Error:** ```

[Error] An unhandled exception has occurred while executing the request. jsreport.Local.JsReportBinaryException: Error rendering report: Error: An error occurred while trying to execute the command:    at onCriticalError ([eval]:36106:25)    at [eval]:36061:13    at tryCatcher ([eval]:9718:23)    at Promise._settlePromiseFromHandler ([eval]:38241:31)    at Promise._settlePromise ([eval]:38298:18)    at Promise._settlePromise0 ([eval]:38343:10)    at Promise._settlePromises ([eval]:38418:18)    at Async._drainQueue ([eval]:4650:16)    at Async._drainQueues ([eval]:4660:10)    at Immediate.Async.drainQueues [as _onImmediate] ([eval]:4534:14)    at processImmediate [as _immediateCallback] (timers.js:396:17) {"originalError":{}}(Original) Error: An error occurred while trying to start daemonized process: An error has occurred when trying to initialize jsreport..    at null.<anonymous> ([eval]:37276:13)    at listener ([eval]:13761:10)    at EventEmitter.emit ([eval]:13849:22)    at _onData ([eval]:85833:8)    at Lazy.<anonymous> ([eval]:52268:13)    at Lazy.<anonymous> ([eval]:52250:19)    at emitTwo (events.js:87:13)    at Lazy.emit (events.js:172:7)    at Lazy.<anonymous> ([eval]:52251:22)    at emitOne (events.js:77:13)    at Lazy.emit (events.js:169:7)    at yieldTo ([eval]:52358:18)    at Function.<anonymous> ([eval]:52396:27)    at Lazy.<anonymous> ([eval]:52364:21)    at emitOne (events.js:77:13)    at Lazy.emit (events.js:169:7)    at Socket.<anonymous> ([eval]:52227:22)    at emitNone (events.js:67:13)    at Socket.emit (events.js:166:7)    at emitReadable_ (_stream_readable.js:419:10)    at emitReadable (_stream_readable.js:413:7)    at readableAddChunk (_stream_readable.js:164:13) {}
   at jsreport.Local.Internal.LocalUtilityReportingService.RenderAsync(String requestString, CancellationToken ct)
   at jsreport.AspNetCore.JsReportMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by pofider** [comment]
Try to use  `.AsUtility().KeepAlive(false)` or 

```csharp
.Configure(cfg => { 
   cfg.AllowLocalFilesAccess().FileSystemStore().BaseUrlAsWorkingDirectory();
   cfg.HttpPort = ...differentPortsForDifferentEnvironments;
   return cfg;
})
```

**Comment by rdevidasvcm-hyniva** [comment]
I have tried with different ports based on the config/environment variable for each environment.  But still I get the error.

**Steps performed:**

Two applications (same project code) are hosted in IIS Server.

Both (web) Sites are running.  Once you can access the site 1 as 1st.  That web site reports will work, the other web site reports generation code throws error.  

Again, 1) stop both application(s) in IIS, 2) Delete c:\Windows\Temp\JsReport folder 3) Run both sites in IIS 4) Access the Site2 run the reports, they will work. 5) Access Site1 and run report it will throw the error.   
Even though I have configured a) Temp Directory, b) AppPath and c) RunInDirectory values while adding to Services collection in Startup.cs

**Here is my startup code:**
`
var tempDirectory = Path.Combine(Directory.GetCurrentDirectory(), "jsTemp");
            var jsReport = new LocalReporting()
                .KillRunningJsReportProcesses()
                .UseBinary(JsReportBinary.GetBinary())
                .RunInDirectory(Path.Combine(Directory.GetCurrentDirectory(), "jsTemp"))
                .Configure(cfg =>
                {
                    cfg.AppPath = tempDirectory;
                    cfg.AllowLocalFilesAccess().FileSystemStore().BaseUrlAsWorkingDirectory();
                    cfg.TempDirectory = tempDirectory;
                    cfg.HttpPort = Configuration["JsReportServerPort"];
                    return cfg;
                })
                .AsUtility().Create() ;
            services.AddJsReport(jsReport);
`

**Here is what I am getting the error:**

`
[Error] An unhandled exception has occurred while executing the request.
jsreport.Local.JsReportBinaryException: Error rendering report: instance has been daemonized and initialized successfully (pid: 18824)rendering has finished with errors:Error: An error occurred while trying to execute the command:    at onCriticalError ([eval]:36106:25)    at [eval]:36061:13    at tryCatcher ([eval]:9718:23)    at Promise._settlePromiseFromHandler ([eval]:38241:31)    at Promise._settlePromise ([eval]:38298:18)    at Promise._settlePromise0 ([eval]:38343:10)    at Promise._settlePromises ([eval]:38418:18)    at Async._drainQueue ([eval]:4650:16)    at Async._drainQueues ([eval]:4660:10)    at Immediate.Async.drainQueues [as _onImmediate] ([eval]:4534:14)    at processImmediate [as _immediateCallback] (timers.js:396:17) {"originalError":{}}(Original) Error: Couldn't connect to remote jsreport server in: http://localhost:5780/C:\Ramesh\\src\THB.App\jsTemp/, Please verify that a jsreport server is running    at [eval]:36149:17    at [eval]:39144:11    at ConcatStream.<anonymous> ([eval]:44860:43)    at emitNone (events.js:72:20)    at ConcatStream.emit (events.js:166:7)    at finishMaybe ([eval]:4229:14)    at afterWrite ([eval]:4115:3)    at nextTickCallbackWithManyArgs (node.js:486:18)    at process._tickCallback (node.js:384:17) {}
   at jsreport.Local.Internal.LocalUtilityReportingService.RenderAsync(String requestString, CancellationToken ct)
   at jsreport.AspNetCore.JsReportMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
`

**Comment by rdevidasvcm-hyniva** [comment]
> Try to use `.AsUtility().KeepAlive(false)` or

I did not get KeepAlive method to add it in the code.  I tried updating to latest stable version

**Comment by pofider** [comment]
> I did not get KeepAlive method to add it in the code. I tried updating to latest stable version

This for sure works with the latest:

```js
 new LocalReporting()
                .UseBinary(JsReportBinary.GetBinary())
                .AsUtility()
                .KeepAlive(false)
                .Create();
```

> Description: Referred Assemblies - jsReport.AspNetCore 1.0.0, jsReport.Binary 1.9.1 and jsReport.Local 1.1.0.

I see you use very old packages. Could you try to update to the latest and try again? There were several fixes in the past versions for supporting parallel usage.

**Comment by pofider** [comment]
I've released jsreport.Binary 3.8.0 as well as the other .net sdk nugets.
Please try it out and reopen the issue if you have further issues.

**Comment by mdudek** [comment]
I'm facing same issue with jsreport.aspnetcore 3.8.0,  jsreport.binary 3.9.0, jsreport.local 3.8.1.  Windows 11, VS 2022, Target framework .NET 6.0.
