### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by imranjalali** [jsreport/jsreport-dotnet#65]
I am facing the following error, I am rendering HTML as PDF (Download). Can anyone help?

Error rendering report: An error ocurred while trying to execute "render" command (3). A critical error occurred while trying to execute the render command (2). An error occurred while trying to start daemonized process: An error has occurred when trying to initialize jsreport, seems like there is already a server running in port: 5488 (1). caused by error (3):-> stackError:    at startCLI (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:127:19)    at async startCommand (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:67:5)    at async startProcessing (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startProcessing.js:195:3)caused by error (2):-> stackError:    at onCriticalError (C:\snapshot\jsreport\packages\jsreport-cli\lib\commands\render.js:304:19)    at C:\snapshot\jsreport\packages\jsreport-cli\lib\commands\render.js:258:14    at async executeCommand (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\executeCommand.js:22:20)    at async Object.handler (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\registerCommand.js:76:9)    at async parseCLI (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:156:3)    at async startCLI (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:121:20)    at async startCommand (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:67:5)    at async startProcessing (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startProcessing.js:195:3)caused by error (1):-> meta = {"code":"EADDRINUSE"}-> stackError: An error has occurred when trying to initialize jsreport, seems like there is already a server running in port: 5488    at Object.<anonymous> (C:\snapshot\jsreport\packages\jsreport-cli\lib\keepAliveProcess.js:157:27)    at Object.listener (C:\snapshot\jsreport\node_modules\eventemitter2\lib\eventemitter2.js:251:10)    at Object.emit (C:\snapshot\jsreport\node_modules\eventemitter2\lib\eventemitter2.js:339:22)    at Object._onData (C:\snapshot\jsreport\node_modules\nssocket\lib\nssocket.js:454:8)    at Lazy.<anonymous> (C:\snapshot\jsreport\node_modules\lazy\lazy.js:91:13)    at Lazy.<anonymous> (C:\snapshot\jsreport\node_modules\lazy\lazy.js:73:19)    at Lazy.emit (node:events:390:28)    at Lazy.<anonymous> (C:\snapshot\jsreport\node_modules\lazy\lazy.js:74:22)    at Lazy.emit (node:events:390:28)    at yieldTo (C:\snapshot\jsreport\node_modules\lazy\lazy.js:181:18)Remote Instance Error: Error:    at C:\snapshot\jsreport\packages\jsreport-cli\lib\instanceHandler.js:31:29    at processTicksAndRejections (node:internal/process/task_queues:96:5)Remote Instance Error: Error:    at Server.setupListenHandle [as _listen2] (node:net:1334:16)    at listenInCluster (node:net:1382:12)    at Server.listen (node:net:1469:7)    at C:\snapshot\jsreport\packages\jsreport-express\lib\main.js:22:12    at new Promise (<anonymous>)    at startAsync (C:\snapshot\jsreport\packages\jsreport-express\lib\main.js:16:10)    at C:\snapshot\jsreport\packages\jsreport-express\lib\main.js:50:14    at Object.start (C:\snapshot\jsreport\packages\jsreport-express\lib\main.js:125:13)    at Object.<anonymous> (C:\snapshot\jsreport\packages\jsreport-express\lib\main.js:327:30)    at async ListenerCollection.fire (C:\snapshot\jsreport\packages\jsreport-core\lib\shared\listenerCollection.js:157:21)
looking for previously daemonized instance in: C:\inetpub\wwwroot\TanFile\App_Data\jsreport-temp\cli\wSock cwd: C:\inetpub\wwwroot\TanFile\bin\jsreportthere is no previously daemonized instance in: C:\inetpub\wwwroot\TanFile\App_Data\jsreport-temp\cli\wSock cwd: C:\inetpub\wwwroot\TanFile\bin\jsreport

**Comment by pofider** [comment]
>  seems like there is already a server running in port: 5488

There is another jsreport instance. Kill it from the taskmgr (node process).

You can also let .net kill all other jsreport node processes using
```js
var rs = new LocalReporting()
     .UseBinary(JsReportBinary.GetBinary())
     .KillRunningJsReportProcesses()
     ...
```

**Comment by imranjalali** [comment]
Thank you for your prompt reply.

I am already doing  it ... from the previous posts. 

`var rs = new LocalReporting()
                .UseBinary(JsReportBinary.GetBinary())
                .KillRunningJsReportProcesses()
                .TempDirectory(Path.Combine((string)AppDomain.CurrentDomain.GetData("DataDirectory"), "jsreport-temp"))
                .AsUtility()
                .Create();`

But that doesn't solve the problem....

**Comment by pofider** [comment]
Did you try to kill node processes in the taskmgr?

**Comment by imranjalali** [comment]
> Did you try to kill node processes in the taskmgr?

Yes I did! 

![image](https://user-images.githubusercontent.com/29058709/201646227-707f950f-b8da-4d46-bf66-5dc9819205c3.png)

**Comment by imranjalali** [comment]
It works fine with sample source code you have provided. But when I deploy in IIS the above error is throwing.

**Comment by imranjalali** [comment]
Now when I kill the node manually following error is appearing? 

Error rendering report: rendering has finished with errors:An error ocurred while trying to execute "render" command (3). A critical error occurred while trying to execute the render command (2). spawn EPERM (1). caused by error (3):-> stackError:    at startCLI (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:127:19)    at processTicksAndRejections (node:internal/process/task_queues:96:5)    at async startCommand (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:67:5)    at async startProcessing (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startProcessing.js:195:3)caused by error (2):-> stackError:    at onCriticalError (C:\snapshot\jsreport\packages\jsreport-cli\lib\commands\render.js:304:19)    at C:\snapshot\jsreport\packages\jsreport-cli\lib\commands\render.js:258:14    at processTicksAndRejections (node:internal/process/task_queues:96:5)    at async executeCommand (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\executeCommand.js:22:20)    at async Object.handler (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\registerCommand.js:76:9)    at async parseCLI (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:156:3)    at async startCLI (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:121:20)    at async startCommand (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:67:5)    at async startProcessing (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startProcessing.js:195:3)caused by error (1):-> stackError:    at Client.render (C:\snapshot\jsreport\packages\nodejs-client\lib\client.js:92:17)    at processTicksAndRejections (node:internal/process/task_queues:96:5)    at async startRender (C:\snapshot\jsreport\packages\jsreport-cli\lib\commands\render.js:321:24)    at async C:\snapshot\jsreport\packages\jsreport-cli\lib\commands\render.js:228:22    at async executeCommand (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\executeCommand.js:22:20)    at async Object.handler (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\registerCommand.js:76:9)    at async parseCLI (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:156:3)    at async startCLI (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:121:20)    at async startCommand (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:67:5)    at async startProcessing (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startProcessing.js:195:3)Remote stack: Error:    at ChildProcess.spawn (node:internal/child_process:412:11)    at Object.spawn (node:child_process:698:9)    at Object.spawn (pkg/prelude/bootstrap.js:1963:27)    at BrowserRunner.start (C:\snapshot\jsreport\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:119:34)    at ChromeLauncher.launch (C:\snapshot\jsreport\node_modules\puppeteer\lib\cjs\puppeteer\node\ChromeLauncher.js:76:16)    at async createBrowser (C:\snapshot\jsreport\packages\jsreport-chrome-pdf\lib\chromePoolStrategy.js:98:26)    at async allocateBrowser (C:\snapshot\jsreport\packages\jsreport-chrome-pdf\lib\chromePoolStrategy.js:113:5)    at async getBrowser (C:\snapshot\jsreport\packages\jsreport-chrome-pdf\lib\chromePoolStrategy.js:23:30)    at async C:\snapshot\jsreport\packages\jsreport-chrome-pdf\lib\conversion.js:11:19    at async execute (C:\snapshot\jsreport\packages\jsreport-chrome-pdf\lib\chromePoolStrategy.js:20:22)
looking for previously daemonized instance in: C:\inetpub\wwwroot\TanFile\App_Data\jsreport-temp\cli\wSock cwd: C:\inetpub\wwwroot\TanFile\bin\jsreportthere is no previously daemonized instance in: C:\inetpub\wwwroot\TanFile\App_Data\jsreport-temp\cli\wSock cwd: C:\inetpub\wwwroot\TanFile\bin\jsreportinstance has been daemonized and initialized successfully (pid: 7280)remote server options:{  "url": "http://localhost:5488/"}rendering with options:{

**Comment by imranjalali** [comment]
I found something strange when I kill Node JS there is different error with partial HTML Rendered.

Here is the output.
Error rendering report: rendering has finished with errors:An error ocurred while trying to execute "render" command (3). A critical error occurred while trying to execute the render command (2). spawn EPERM (1). caused by error (3):-> stackError:    at startCLI (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:127:19)    at processTicksAndRejections (node:internal/process/task_queues:96:5)    at async startCommand (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:67:5)    at async startProcessing (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startProcessing.js:195:3)caused by error (2):-> stackError:    at onCriticalError (C:\snapshot\jsreport\packages\jsreport-cli\lib\commands\render.js:304:19)    at C:\snapshot\jsreport\packages\jsreport-cli\lib\commands\render.js:258:14    at processTicksAndRejections (node:internal/process/task_queues:96:5)    at async executeCommand (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\executeCommand.js:22:20)    at async Object.handler (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\registerCommand.js:76:9)    at async parseCLI (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:156:3)    at async startCLI (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:121:20)    at async startCommand (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:67:5)    at async startProcessing (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startProcessing.js:195:3)caused by error (1):-> stackError:    at Client.render (C:\snapshot\jsreport\packages\nodejs-client\lib\client.js:92:17)    at processTicksAndRejections (node:internal/process/task_queues:96:5)    at async startRender (C:\snapshot\jsreport\packages\jsreport-cli\lib\commands\render.js:321:24)    at async C:\snapshot\jsreport\packages\jsreport-cli\lib\commands\render.js:228:22    at async executeCommand (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\executeCommand.js:22:20)    at async Object.handler (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\registerCommand.js:76:9)    at async parseCLI (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:156:3)    at async startCLI (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:121:20)    at async startCommand (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startCommand.js:67:5)    at async startProcessing (C:\snapshot\jsreport\packages\jsreport-cli\lib\commander\startProcessing.js:195:3)Remote stack: Error:    at ChildProcess.spawn (node:internal/child_process:412:11)    at Object.spawn (node:child_process:698:9)    at Object.spawn (pkg/prelude/bootstrap.js:1963:27)    at BrowserRunner.start (C:\snapshot\jsreport\node_modules\puppeteer\lib\cjs\puppeteer\node\BrowserRunner.js:119:34)    at ChromeLauncher.launch (C:\snapshot\jsreport\node_modules\puppeteer\lib\cjs\puppeteer\node\ChromeLauncher.js:76:16)    at async createBrowser (C:\snapshot\jsreport\packages\jsreport-chrome-pdf\lib\chromePoolStrategy.js:98:26)    at async allocateBrowser (C:\snapshot\jsreport\packages\jsreport-chrome-pdf\lib\chromePoolStrategy.js:113:5)    at async getBrowser (C:\snapshot\jsreport\packages\jsreport-chrome-pdf\lib\chromePoolStrategy.js:23:30)    at async C:\snapshot\jsreport\packages\jsreport-chrome-pdf\lib\conversion.js:11:19    at async execute (C:\snapshot\jsreport\packages\jsreport-chrome-pdf\lib\chromePoolStrategy.js:20:22)
looking for previously daemonized instance in: C:\Users\DefaultAppPool\AppData\Local\Temp\jsreport\cli\wSock cwd: C:\inetpub\wwwroot\TanFile\bin\jsreportthere is no previously daemonized instance in: C:\Users\DefaultAppPool\AppData\Local\Temp\jsreport\cli\wSock cwd: C:\inetpub\wwwroot\TanFile\bin\jsreportinstance has been daemonized and initialized successfully (pid: 10144)remote server options:{  "url": "http://localhost:5488/"}rendering with options:{  "$id": "1",  "template": {    "$id": "2",    "content": "\r\n\r\n\r\n<!DOCTYPE html>\r\n<html dir=\"rtl\" lang=\"ar\">\r\n<head>\r\n    <meta charset=\"UTF-8\" />\r\n    <title>GAC - Notice</title>\r\n    <link rel=\"stylesheet\" href=\"/test/Content/bootstrap.min.css\" />\r\n    <link rel=\"stylesheet\" href=\"/test/Content/style.css\" />\r\n    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\r\n    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Kufi+Arabic:wght@400;600;700&display=swap\" rel=\"stylesheet\" />\r\n    <script src=\"/test/Scripts/jquery-3.3.1.min.js\"></script>\r\n</head>\r\n    <body>\r\n        <div class=\"container pm-certificate-container\">\r\n            <div class=\"outer-border\"></div>\r\n            <div class=\"inner-border\"></div>\r\n\r\n            <div class=\"pm-certificate-border col-xs-12\">\r\n                <div class=\"row pm-certificate-header\">\r\n                    <div class=\"col-xs-12\">\r\n                        <div class=\"row\">\r\n                            <div class=\"col-xs-4 pm-credits-text\" style=\"padding-left: 30px\">\r\n                                <span class=\"pm-empty-space block\"></span>\r\n                                <p>&nbsp;</p>\r\n                                <p class=\"bold block\">Ø±Ù‚Ù… Ø§Ù„Ø¥Ø´Ø¹Ø§Ø±: <span>157</span></p>\r\n                                <p class=\"bold block\">ØªØ§Ø±ÙŠØ® Ø§Ù„Ø¥Ø´Ø¹Ø§Ø±: <span>11/13/2022 3:56:00 PM Ù…</span></p>\r\n                            </div>\r\n                            <div class=\"col-xs-3\">\r\n                                \r\n                            </div>\r\n                            <div class=\"col-xs-5 pm-certified text-center\" style=\"padding-right: 30px\">\r\n                                <span class=\"pm-empty-space block\"></span>\r\n                                <img  src=\"/test/Content/images/GAC-logo-1.svg\" alt=\"GAC logo\" />\r\n                            </div>\r\n                        </div>\r\n                    </div>\r\n\r\n                    <div class=\"pm-certificate-title col-xs-12 text-center\">\r\n                        <p>&nbsp;</p>\r\n                        <h3 style=\"font-weight: 700; color: #6f7576\">Ø¥Ù†Ø°Ø§Ø± Ø£ÙˆÙ„ÙŠ Ø¨Ø³Ø¯Ø§Ø¯ ØºØ±Ø§Ù…Ø© Ù…Ø§Ù„ÙŠØ©</h3>\r\n                        \r\n                    </div>\r\n                </div>\r\n\r\n                <div class=\"row pm-certificate-body\">\r\n                    <div class=\"pm-certificate-block\">\r\n                        <div class=\"col-xs-12\">\r\n                            <div class=\"col-xs-12\">\r\n                                <div class=\"row\">\r\n                                    <table class=\"table\" style=\"border-collapse: separate; border-spacing: 10px\">\r\n                                        <tr>\r\n                                            <th scope=\"row\" class=\"pm-name-text green-bg text-center\" style=\"width: 30%; border: 1px solid #60a318\">\r\n                                                <img style=\"padding-bottom: 10px\" src=\"/test/Content/images/icon-1.svg\" width=\"25px\" alt=\"\" />\r\n                                                <br />\r\n                                                Ø§Ø³Ù… Ø§Ù„Ù…Ù†Ø´Ø£Ø©\r\n                                                <br /><span style=\"font-size: 80%\">Ø§Ù„ØµØ§Ø¯Ø± Ø¨Ø­Ù‚Ù‡Ø§ Ø§Ù„ØºØ±Ø§Ù…Ø© Ø§Ù„Ù…Ø§Ù„ÙŠØ©</span>\r\n                                            </th>\r\n                                            <td class=\"pm-english-text grey-bg\" style=\"border: 1px solid #ddd\">ØªØ¬Ø±ÙŠØ¨ÙŠ\r\n                                                <br /><span style=\"font-size: 80%\">Ø±Ù‚Ù… Ø§Ù„Ø³Ø¬Ù„ Ø§Ù„ØªØ¬Ø§Ø±ÙŠ: 2035807359</span>\r\n                                            </td>\r\n                                        </tr>\r\n                                        <tr>\r\n                                            <th scope=\"row\" class=\"pm-name-text green-bg text-center\" style=\"border: 1px solid #60a318\">\r\n                                                <img style=\"padding-bottom: 10px\" src=\"/test/Content/images/icon-2.svg\" width=\"25px\" alt=\"\" /> <br />Ø§Ù„Ø¹Ù†ÙˆØ§Ù† Ø§Ù„ÙˆØ·Ù†ÙŠ\r\n                                            </th>\r\n                                            <td class=\"pm-english-text grey-bg\" style=\"border: 1px solid #ddd\">\r\n                                                (6545) Ù…Ø­Ù…Ø¯ Ø¨Ø±Ù†Ø§ÙˆÙŠ - Ø­ÙŠ Ø§Ù„Ø±ÙˆØ¶Ø¯Ø© - Ø§Ù„Ø±ÙŠØ§Ø¶ Ø§Ù„Ø±Ù…Ø² Ø§Ù„Ø¨Ø±ÙŠØ¯ÙŠ (11492) Ø§Ù„Ø¥Ø¶Ø§ÙÙŠ (6545)\r\n                                            </td>\r\n                                        </tr>\r\n                                        <tr>\r\n                                            <th scope=\"row\" class=\"pm-name-text green-bg text-center\" style=\"border: 1px solid #60a318\">\r\n                                                <img style=\"padding-bottom: 10px\" src=\"/test/Content/images/icon-3.svg\" width=\"25px\" alt=\"\" /> <br />Ø§Ù„Ù…Ù‡Ù„Ø© Ø§Ù„Ù…Ø­Ø¯Ø¯Ø© Ù„Ù„Ø³Ø¯Ø§Ø¯\r\n                                            </th>\r\n                                            <td class=\"pm-english-text grey-bg\" style=\"border: 1px solid #ddd\">(15) ÙŠÙˆÙ… Ø¹Ù…Ù„ Ù…Ù† ØªØ§Ø±ÙŠØ® Ù‡Ø°Ø§ Ø§Ù„Ø¥Ø´Ø¹Ø§Ø±</td>\r\n                                        </tr>\r\n                                        <tr>\r\n                                            <th scope=\"row\" class=\"pm-name-text green-bg text-center\" style=\"border: 1px solid #60a318\">\r\n                                                <img style=\"padding-bottom: 10px\" src=\"/test/Content/images/icon-4.svg\" width=\"30px\" alt=\"\" /> <br />Ù…Ù‚Ø¯Ø§Ø± Ø§Ù„ØºØ±Ø§Ù…Ø© Ø§Ù„Ù…Ø§Ù„ÙŠØ©\r\n                                            </th>\r\n                                            <td class=\"pm-english-text grey-bg\" style=\"border: 1px solid #ddd\">\r\n                                                ()<br /><span style=\"font-size: 80%\">(ØµÙØ± Ø±ÙŠØ§Ù„)</span>\r\n                                            </td>\r\n                                        </tr>\r\n                                        <tr>\r\n                                            <th scope=\"row\" class=\"pm-name-text green-bg text-center\" style=\"border: 1px solid #60a318\">\r\n                                                <img style=\"padding-bottom: 10px\" src=\"/test/Content/images/icon-5.svg\" width=\"25px\" alt=\"\" /> <br />Ø±Ù‚Ù… Ø§Ù„Ù‚Ø±Ø§Ø± / Ø§Ù„Ø­ÙƒÙ… ÙˆØªØ§Ø±ÙŠØ®Ù‡ <br /><span style=\"font-size: 80%\">Ø§Ù„ØµØ§Ø¯Ø± Ø¨Ø­Ù‚ Ø§Ù„Ù…Ù†Ø´Ø£Ø©</span>\r\n                                            </th>\r\n                                            <td class=\"pm-english-text grey-bg\" style=\"border: 1px solid #ddd\">\r\n                                                Ù‚Ø±Ø§Ø± Ù„Ø¬Ù†Ø© Ø§Ù„ÙØµÙ„ ÙÙŠ Ù…Ø®Ø§Ù„ÙØ§Øª Ù†Ø¸Ø§Ù… Ø§Ù„Ù…Ù†Ø§ÙØ³Ø©<br /><span style=\"font-size: 100%\">Ø±Ù‚Ù… (000) ÙˆØªØ§Ø±ÙŠØ® 11/8/2022 12:00:00 AM Ù…</span>\r\n                                            </td>\r\n                                        </tr>\r\n                                        <tr>\r\n                                            <th scope=\"row\" class=\"pm-name-text green-bg text-center\" style=\"border: 1px solid #60a318\">\r\n                                                <img style=\"padding-bottom: 10px\" src=\"/test/Content/images/icon-6.svg\" width=\"25px\" alt=\"\" /> <br />Ù‚Ù†ÙˆØ§Øª Ø§Ù„Ø³Ø¯Ø§Ø¯\r\n                                            </th>\r\n                                            <td class=\"pm-english-text grey-bg\" style=\"border: 1px solid #ddd\">\r\n                                                <ul style=\"text-align: right\">\r\n                                                    <li style=\"padding-bottom: 10px\">\r\n                                                        Ø¨Ù…ÙˆØ¬Ø¨ Ø´ÙŠÙƒ Ù…ØµØ±ÙÙŠ (Ù…ØµØ¯Ù‘Ù‚) Ø¨Ø§Ø³Ù… Ø§Ù„Ù‡ÙŠØ¦Ø© Ø§Ù„Ø¹Ø§Ù…Ø© Ù„Ù„Ù…Ù†Ø§ÙØ³Ø©/ Ø§Ù„ØºØ±Ø§Ù…Ø§ØªØŒ ÙŠØ³Ù„Ù… Ù„Ù„Ù‡ÙŠØ¦Ø© Ø§Ù„Ø¹Ø§Ù…Ø© Ù„Ù„Ù…Ù†Ø§ÙØ³Ø©.\r\n                                                    </li>\r\n                                                    <li style=\"padding-bottom: 10px\">\r\n                                                        Ø£Ùˆ Ø§Ù„Ø¥ÙŠØ¯Ø§Ø¹ ÙÙŠ Ø­Ø³Ø§Ø¨ Ø§Ù„Ù‡ÙŠØ¦Ø© Ø§Ù„Ø¹Ø§Ù…Ø© Ù„Ù„Ù…Ù†Ø§ÙØ³Ø© Ù„Ø¯Ù‰ Ø§Ù„Ø¨Ù†Ùƒ Ø§Ù„Ù…Ø±ÙƒØ²ÙŠ Ø±Ù‚Ù… (SA6801100001230401000017) Ù…Ø¹ ØªØ²ÙˆÙŠØ¯ Ø§Ù„Ù‡ÙŠØ¦Ø© Ø¨Ø¥Ø´Ø¹Ø§Ø± Ù…Ù† Ø§Ù„Ø¨Ù†Ùƒ\r\n                                                        ÙŠÙÙŠØ¯ Ø¨Ø³Ø¯Ø§Ø¯ Ù…Ø¨Ù„Øº Ø§Ù„ØºØ±Ø§Ù…Ø©.\r\n                                                    </li>\r\n                                                    <li>ÙØ§ØªÙˆØ±Ø© Ø±Ù‚Ù… ()</li>\r\n                                                </ul>\r\n                                            </td>\r\n                                        </tr>\r\n                                        <tr>\r\n                                            <th scope=\"row\" class=\"pm-name-text green-bg text-center\" style=\"border: 1px solid #60a318\">\r\n                                                <img style=\"padding-bottom: 10px\" src=\"/test/Content/images/icon-7.svg\" width=\"25px\" alt=\"\" /> <br />Ù„Ù„Ø§Ø³ØªÙØ³Ø§Ø±Ø§Øª\r\n                                            </th>\r\n                                            <td class=\"pm-english-text grey-bg\" style=\"border: 1px solid #ddd\">\r\n                                                Ø§Ù„Ø¨Ø±ÙŠØ¯ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ: enforcement@gac.gov.sa<br /><span style=\"font-size: 100%\">Ø§Ù„Ù‡Ø§ØªÙ: (0114406666) ØªØ­ÙˆÙŠÙ„Ø© Ø±Ù‚Ù… 21547</span>\r\n                                            </td>\r\n                                        </tr>\r\n                                    </table>\r\n                                </div>\r\n                            </div>\r\n                        </div>\r\n                    </div>\r\n\r\n                    <div class=\"pm-certificate-footer text-center\">\r\n                        <div class=\"col-xs-3\" style=\"text-align: right\">\r\n                        </div>\r\n                        <div class=\"col-xs-9\">\r\n                            <h4>Ù‡Ø°Ù‡ Ø§Ù„ÙˆØ«ÙŠÙ‚Ø© Ù…Ø±Ø³Ù„Ø© Ù…Ù† Ø§Ù„Ù†Ø¸Ø§Ù… Ø§Ù„Ø¢Ù„ÙŠ ÙˆÙ„Ø§ ØªØ­ØªØ§Ø¬ Ø¥Ù„Ù‰ ØªÙˆÙ‚ÙŠØ¹</h4>\r\n                            <p>&nbsp;</p>\r\n                            <div class=\"row\">\r\n                                <img src=\"/test/Content/images/socials-footer.svg\" width=\"550px\" alt=\"\" />\r\n                            </div>\r\n                        </div>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n    \r\n            </body>\r\n     <script src=\"/test/Scripts/bootstrap.min.js\"></script>\r\n</html>\r\n\r\n",    "engine": "none",    "recipe": "chrome-pdf"  },  "options": {    "$id": "3",    "base": "http://localhost//test",    "debug": {      "$id": "4",      "logsToResponseHeader": true    }  }}

**Comment by pofider** [comment]
Don't you have IIS number of worker processes configured to higher than 1?"

**Comment by imranjalali** [comment]
It's  configured as 1 

![image](https://user-images.githubusercontent.com/29058709/201846116-55a18999-ff91-4218-bea2-72549cb22776.png)

Late yesterday, I mange to  render  by adding 

` var rs = new LocalReporting()
              .UseBinary(JsReportBinary.GetBinary())
                  .KillRunningJsReportProcesses()
                  .TempDirectory(Path.Combine((string)AppDomain.CurrentDomain.GetData("DataDirectory"), "jsreport-temp"))
                  .Configure(cfg => cfg.AllowedLocalFilesAccess().BaseUrlAsWorkingDirectory())
                  .AsUtility().KeepAlive(false)
                  .Create();

           filters.Add(new JsReportFilterAttribute(new ReportingService("http://10.112.8.21:5488/")));`


Now it is showing...

![image](https://user-images.githubusercontent.com/29058709/201846943-2759a886-27c2-46f0-99a4-f27b3b17ffa9.png)

**Comment by pofider** [comment]
Hmm, I will need some instructions on how to replicate this.

I cloned and compiled this example
https://github.com/jsreport/jsreport-dotnet-example-net-webapp

I created a new website in IIS without doing any extra configs. I open the app and things work for me.

Could you give me some steps on how to replicate your issue? The best is to start from scratch, create a new VM lets say in Azure, with windows server xxx, install IIS, and deploy an app...

**Comment by kajdzo** [comment]
I'm having the same issue here. Works awesome on my local machine but the minute I publish it to EC2 windows IIS same thing happens.  Do you guys have any solution ?
![image](https://user-images.githubusercontent.com/10382570/206924789-b5e077a6-e2ba-45a2-bbb5-f3d5f9fe3bdd.png)
Here is also peace of my code.
![image](https://user-images.githubusercontent.com/10382570/206924952-5fde119f-56a1-4647-b997-f42ca95d5d68.png)

**Comment by pofider** [comment]
@kajdzo I would love to replicate it and fix it. Would you please provide me with the exact steps on what to do to replicate this? What exact image do you use? Windows Server 2022 base? What do you do in VM, do you provide the user running the app the permissions to write to the app folder? Do you use the default website in IIS or do you create a new one? Do you configure IIS in any way? What .net version do you use?

**Comment by kajdzo** [comment]
First of all,  thanks for quick response. I'm on Windows Server 2022. Using default IIS site. .NET 6. Pretty much everything is out of the box.  While debugging this issue I have added user with Full access to everything.
![image](https://user-images.githubusercontent.com/10382570/206927121-1d9fb413-86af-42af-a0ff-bbbd58bf05ca.png)
My code is pasted in previous post. And here is a list of my nugets. 
![image](https://user-images.githubusercontent.com/10382570/206927150-07b9135f-323d-4c0a-adbf-666d9b8e38df.png)
I also installed nodejs on the VM.

**Comment by pofider** [comment]
I've tried it and have had no issues. Please try the same and let me know if it works.
We will need to find out what is different to isolate the problem.

## The app
https://github.com/jsreport/jsreport-dotnet-example-webapp
I used publish to file system

![image](https://user-images.githubusercontent.com/2041960/207022042-9207222a-d5f7-4bf3-9aea-4252291a7d80.png)

## The server
I have a fresh EC2 Windows Server 2022 Base T2 medium
I've installed IIS there using Server Manager and "Add roles and features"
![image](https://user-images.githubusercontent.com/2041960/207022294-b5463c07-6dab-4236-bffe-ed3e5985d21f.png)
I've installed also .net ASP.NET Core Runtime 6.0.11 Windows Hosting Bundle from the link here
https://dotnet.microsoft.com/en-us/download/dotnet/6.0
In IIS I used "Add Website.." with the new app pool and targetting the folder with the app deployment and explicit port 5000

Then I opened the app, and I see the pdf renders fine.

**Comment by kajdzo** [comment]
I won't be able to test it untill tomorrow but as soon as I do I'll post results. Thanks!
